### ISSUE TITLE
Slow performance on 'larger' jpg files

### ISSUE THREAD

**Issue by ghost** [sbrunner/deskew#10]
Hi Stéphane,
thank you for your nice repo.
I have been using it to deskew jpg files of scanned documents.
I was noticing that I get very poor performance when trying to detect the skew of files larger than approx. 5mb.
It takes like 3 minutes for one file. Do you have an idea what I could try to speed this up? 

Thanks a lot and best regards!

**Comment by selvaraj-andavar** [comment]
Hey,

Resizing the image could speeds up the performance, but i was seeing few problems with determine angles.

https://github.com/sbrunner/deskew/issues/12

Thanks!
**_Selva_**
