### ISSUE TITLE
Different Angle Predictions at Different Image scales/sizes

### ISSUE THREAD

**Issue by selvaraj-andavar** [sbrunner/deskew#12]
Hey There,

I've been using this Repo for more than a quarter. I use to deal with the images of ~4000 x 5000 resoultions.
The Determine skew is resulting different angles at different scales.

I've tried to resize the image to its 1 scale, 0.5 scale, 0.25 scale and so on...

Here is the results,
**iteration -> Scale(fx, fy) -> angle -> resolution**
0 --> 1 --> 0.0 --> (5500, 4250)
1 --> 0.5 --> 0.0 --> (2750, 2125)
2 --> 0.25 --> 0.0 --> (1375, 1062)
3 --> 0.125 --> 0.0 --> (688, 531)
**4 --> 0.0625 --> 0.5027932960893793 --> (344, 266)**

You can see at 0.0625 scale angle has been figured out and after correcting the angle image was looking good at least for naked eye.

Please let me know your thoughts.

**Comment by briliantnugraha** [comment]
Hi @selvaraj-andavar, I guess that you could solve the slow performance on "larger" jpg files by:
- Getting the angle (determine_skew) using small-scaled image.
- let say in your case (4000x5000) to 0.125/12.5% of it's original size.
And also, a little bit of angle error is normal I guess. Whenever you resize it, there will be a lost of information, blurred edges etc. Hence 1-5 degree of error does make sense to me.

Hope it helps, cheers~

**Comment by woctezuma** [comment]
Yes, 0.5 degree is not much.

It would have been interesting to test the procedure with a more skewed image.

**Comment by sbrunner** [comment]
Usually, I use it with big images and I get good result.
I think that it can be good to have an image collection of problematic images to improve the tool :-)
