### ISSUE TITLE
Request for changelog and tagged versions

### ISSUE THREAD

**Issue by stefan6419846** [sbrunner/deskew#202]
I just discovered your library and considered using it, but quickly got aware that at least Python 3.8 is required which I am not able to upgrade to yet. Going through the list of releases on PyPI, 0.10.29 seems to be the last version supporting Python < 3.8.

Such things would be much easier if there was a changelog for the different releases as well as tagged versions on GitHub. For now there seem to be tons of new package releases on PyPI to skim through - given that there are 25 releases in 2022 already, this corresponds to more than one release per week, which is hard to keep up with.

With a changelog, it would be easier to check how important an update might be, as well as some easy way to detect deprecations like for Python < 3.8. With GitHub releases or tags comparing the actual differences between the different versions would be possible as well.

**Comment by sbrunner** [comment]
In fact, I don't fins any changes around 0.10.29 that make it incompatible with Python <3.8, what's make it incompatible with python 3.8?

**Comment by stefan6419846** [comment]
It seems like *pip* picks up the trove classifier introduced in https://github.com/sbrunner/deskew/commit/df7b06cc7255832758299f2ee0cc5aa27d2fdd8b - at least this is the only relevant commit between 0.10.29 and 0.10.30: https://github.com/sbrunner/deskew/compare/0.10.29...0.10.30

Recent changes explicitly define Python >= 3.8: https://github.com/sbrunner/deskew/blob/fba9c6a9e57ad997e3027a2c6aebe73bf638d177/pyproject.toml#L41

**Comment by sbrunner** [comment]
I just create a new version that should work with Python 3.7, is it working for you?

**Comment by stefan6419846** [comment]
Yes, judging from a quick test, it seems to work now using Python 3.7: https://github.com/stefan6419846/gha-tests/runs/6896232016. Thank you.

**Comment by sbrunner** [comment]
Thanks :-)
Just notes that I will remove the Python 3.7 in next release because resent versions of numpy will not support python 3.7...
