### ISSUE TITLE
ValueError: the input array must have size 3 along 'channel axis'

### ISSUE THREAD

**Issue by jasondalycan** [sbrunner/deskew#278]
I am running this against a PNG file of a completed and scanned survey form and am receiving the following error:

**ValueError: the input array must have size 3 along 'channel axis', got (3416, 2645)**

I'm using the deskew cli with no optional parameters as input (i.e. I'm running `deskew myimage.png`).  My python version is 3.9 on Debian 11.

**Comment by jasondalycan** [comment]
I did more testing and noticed that this is occuring because the image is already grayscale (thus the rgb2gray is failing).  Perhaps this should be handled gracefully (i.e. check if image is already grayscale and then ignore this step).  If I use the library directly (instead of the CLI) and skip converting to grayscale the deskewing is working as expected.

**Comment by Wyzix33** [comment]
Still getting this on cli...
