### ISSUE TITLE
Incorrect Angles

### ISSUE THREAD

**Issue by bmoscon** [sbrunner/deskew#28]
Hello

I've tried using the `determine_skew` function, and have had limited success. If take an image rotate clockwise roughly 15 degrees, the function correctly gives me an angle of 15 degrees. If I provide an image rotate roughly 15 degrees counter clockwise, I get the same result, 15 degrees. I'd expect to get -15 or or 345, not 15. If I've missed something, I apologize. There isn't much to go on from the readme, so I'm not sure if there are limitations to this (perhaps it only works with smaller angles?) or if I am using the library incorrectly. 

If I rotate an image -1 and check it with `determine_skew`, it correctly tells me its angle of rotation is -1. Are there known limitations here?

**Comment by sbrunner** [comment]
For me it's working:
```
convert tests/deskew-5.png -rotate -3.410 d.png
convert d.png -rotate 15 dp.png
convert d.png -rotate -15 dm.png
deskew dp.png 
Estimated angle: 15.083798882681563
deskew dm.png 
Estimated angle: -15.083798882681563
```
And in code:
```
from deskew import determine_skew
from skimage import io
print(determine_skew(io.imread('dp.png')), determine_skew(io.imread('dm.png')))
```
=> 15.083798882681563 -15.083798882681563

It's probably that your image is not well-supported...
