### ISSUE TITLE
different angles than expected

### ISSUE THREAD

**Issue by HeChengHui** [sbrunner/deskew#311]
Version: deskew-1.3.3

```
def deskew(image):
    grayscale = rgb2gray(image)
    angle = determine_skew(grayscale)
    print(angle)
    rotated = rotate(image, angle, resize=True) * 255
    return rotated.astype(np.uint8)

def display_avant_apres(_original):
    dpi = matplotlib.rcParams['figure.dpi']

    image = io.imread(_original)
    height, width, _ = image.shape
    figsize = width / float(dpi), height / float(dpi)
    plt.figure(figsize=figsize)

    plt.subplot(1, 2, 1)
    plt.imshow(image)
    plt.subplot(1, 2, 2)
    plt.imshow(deskew(image))

display_avant_apres("input.jpeg")
```

>> -7.999999999999998
![image](https://user-images.githubusercontent.com/84503515/200481515-077d1c59-da49-4b89-a68a-c5cf01403a8f.png)

Doesn't seem to match what is demonstrated in the README, and generally doesn't work properly with +-90deg rotated images.

with `angle_pm_90=True` made it upside down. Any fixes? using

![image](https://user-images.githubusercontent.com/84503515/200481781-59c03206-4623-4acd-ae5c-213c12e56669.png)

**Comment by woctezuma** [comment]
For the first case, this looks normal due to the limitations mentioned in the README.

> The return angle is between -45 and 45 degrees to don't arbitrary change the image orientation.

**Comment by HeChengHui** [comment]
@woctezuma 
doing that works for the example image, but not always for the images I have. Guess best to avoid landscape images if possible.
