### ISSUE TITLE
cli.py argparse missing types, causes errors

### ISSUE THREAD

**Issue by DVexile** [sbrunner/deskew#392]
The parser.add_argument lines in main() in cli.py do not include a type which results in the arguments being passed as a string further in the code causing run time errors when they are compared with numerics.  Adding the following types fixes things:

--sigma type=float
--num-peaks type=int
--num-angles type=int

Sorry - I'm a gidiot who doesn't understand git so I haven't pushed the fixes myself.  Thanks for the wonderful library!

**Comment by sbrunner** [comment]
Thanks for the notification, this will be fixed with #394 :-)
