### ISSUE TITLE
num-angles not passed in cli.py

### ISSUE THREAD

**Issue by DVexile** [sbrunner/deskew#393]
In cli.py the argument --num-angles is never used.  It should be added to the call to determine_skew (i.e. add num_angles=options.num_angles to the parameter list being passed).  Whatever the default is appears to fairly coarse and since num-angles is ignored it makes it appear the code does nothing when using the CLI on many kinds of files with small rotations.

Again, apologies for not just pushing a change since I'm a troglodyte.  Thanks again for the nice library!

**Comment by sbrunner** [comment]
Thanks, this will be fixed with #394
