### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by hacksider** [sbrunner/deskew#4]
Hi there! Just want to ask how to run this properly as I can't seem to make it run just using the cli. Do I need to install other stuffs aside from

scikit image
numpy

**Comment by sbrunner** [comment]
No, you shouldn't..., Can you provide more information on what you exactly do?

**Comment by Billwall2020** [comment]
Hi! First of all, thanks a lot for this great deskewing tool. Is there a possibility to merge it to one python file where the image path is given manually through cv2.imread('...') directly in the code without using the terminal input? I am currently working on a small test project where I want to put all image processing steps to one python file and the file path is given as an input manually in the code (no parsing etc.). Thanks a lot in advance! for your help!

**Comment by sbrunner** [comment]
In the deskew module you have a function for that :-) :
https://github.com/sbrunner/deskew/blob/master/deskew/__init__.py#L103-L108
