### ISSUE TITLE
can we customize background mask ?

### ISSUE THREAD

**Issue by Lakhankumawat** [sbrunner/deskew#431]
Hi thanks for the library, i explored various libraries so far to deskew the image but the one you developed gives far better results then rest.

have a doubt

can we customize the background ? i went through the docs but did not found anything related 

here is my image
![output](https://github.com/sbrunner/deskew/assets/55774240/1700ab71-1669-453e-83a1-c5ab44d8de1d)

as you can see background by default is set to black.

**Comment by sbrunner** [comment]
Thanks :-)

In the cli you have an argument `--background` :-)
