### ISSUE TITLE
Support 3.12 on PyPI

### ISSUE THREAD

**Issue by mikicz** [sbrunner/deskew#483]
Hi!

I tried to upgrade one of my projects to 3.12 and I found I was blocked on this package, with the following error:

```
The current project's supported Python range (>=3.12,<3.13) is not compatible with some of the required packages Python requirement:
  - deskew requires Python >=3.8,<3.12, so it will not be satisfied for Python >=3.12,<3.13
```

I checked the current code and it seems that on `master` 3.12 should be supported.

Would it please be possible to make a release to PyPI which would support 3.12? 

I would be happy to help with anything if there's something blocking it.

Thanks,
Miki

**Comment by sbrunner** [comment]
I just do the version 1.5.1 that should resolve the issue :-)

**Comment by mikicz** [comment]
Thanks for the quick turn-around! I was able to lock the dependencies now
