### ISSUE TITLE
Updated binaries?

### ISSUE THREAD

**Issue by vivadavid** [sbrunner/deskew#498]
Hi,

Considering that version 1.5.1 was released last month, I wanted to know you intend to update the binaries for the CLI Tool and the GUI Frontend. These are the latest versions you can find on the web:

Deskew CLI Tool v1.30. Posted on: June 19, 2019.
GUI Frontend for Deskew. Posted on: December 4, 2018.

By the way, I was finally able to access the web on https://galfar.vevb.net/wp/projects/deskew/, but the first time I try, there was a weird webpage with a robot and message to click on something to prove that I wasn't a bot.

Thanks!

**Comment by sbrunner** [comment]
You are not speaking about the same project...
Event if have have the same name :-)

**Comment by vivadavid** [comment]
You're right, @sbrunner ! There was a confusion on my part. Sorry about that!
