### ISSUE TITLE
Tool stopped working

### ISSUE THREAD

**Issue by utsavrai** [sbrunner/deskew#547]
I can no longer import deskew or run as a command line tool, it is lagging/processing indefinitely.

**Comment by sbrunner** [comment]
Can you provide additional information about what you are doing?
Like Python version deskew version used code?
If I try with Python 3.10:
```
pip install -U deskew
python -c 'import deskew'
```
It's working (no indefinite time to import).

**Comment by utsavrai** [comment]
The issue persists with python 3.10.14 on ubuntu 22.04 and I am using conda environment, any idea what could be the issue? Can you please specify which exact version of python you are using

**Comment by utsavrai** [comment]
Thanks @sbrunner for the prompt replies. The issue was with my conda environment, on a new environment I am able to import. I will close the issue.
