### ISSUE TITLE
Which is the original repository?

### ISSUE THREAD

**Issue by SaschaHeyer** [sbrunner/deskew#8]
Hi Folks,

does anybody know which is the original repository?

https://github.com/sbrunner/deskew
or
https://github.com/kakul/Alyn

Best regards
Sascha

**Comment by sbrunner** [comment]
As it's written at the end of this page https://github.com/sbrunner/deskew it's Alyn :-)

**Comment by SaschaHeyer** [comment]
Well, that was fast =)
Thanks

**Comment by hummingbird1989** [comment]
What's the preferred method to install this library?

**Comment by sbrunner** [comment]
`pip install deskew` ...

**Comment by woctezuma** [comment]
> `pip install deskew` ...

I am always a bit wary about `pip-installing` packages without making sure that the package was uploaded to PyPI by the owner of the repository. It may be worth to mention it in the README that the package on PyPI is yours, so that one does not have to check.
- https://pypi.org/project/deskew/
